### ISSUE TITLE
Just some feedback

### ISSUE THREAD

**Issue by artelse** [ddvk/remarkable-touchgestures#2]
Compiled and installed the program. It all works, but a few notes:
- swipe up and down functionality reversed in the readme.md in relation to code,
- spacing of TwoWideTap defined as 700 is much larger than the stated 10cm which is confusing for the novice like myself ;)

Would it make sense to merge in the two button (left + right) touch disable functionality of LinusCDE's [rmTouchToggler](https://github.com/LinusCDE/rmTouchToggler)?

In your todo you mention "draw primitives by injecting pen input (lines, rectangles)". Do you have plans to add this functionality to xochitl? That is so missing right now.

Great to see this dev activity for the reMarkable.

**Comment by ddvk** [comment]
all valid points and sorry for the late reply, haven't had time to work on this project (life/lazy), but still plan to(as i'm using it daily myself and there things that i need (1 click TOC opening etc)

the gesture got reversed during some refactoring and forgot to fix it in the readme.

i can add the touch disable stuff.

the graphics primitives stuff, the idea is, hold finger, tap with the pen 2 points and you get a line or rectangle by faking the pen input, but as mentioned time :>

thanks for the feedback

**Comment by artelse** [comment]
Thanks for the response!
I compiled it, changed some minor stuff like disabling left/right tap as swipe is less prone to erroneous activation. Recently compiled it again for a small change and had a problem with not finding `env.h`. Hadn't changed anything in my setup. As a workaround changed it to `envz.h` because this is what I could find. Any idea why it misses that header?
For drawing would love to have primitive or better vector drawing support. But we might have to wait for rM to implement that.

**Comment by ddvk** [comment]
did you source the poky env vars first? (source /opt/poky/2.1.3/environment-setup-cortexa9hf-neon-poky-linux-gnueabi)
the file env.h is in the sysroot
`/opt/poky/2.1.3/sysroots/cortexa9hf-neon-poky-linux-gnueabi/usr/src/debug/util-linux/2.27.1-r0/util-linux-2.27.1/include/env.h`

**Comment by artelse** [comment]
Yes, I source it as described and worked previously. I can also see the header in the right location. But make cannot find `env.h`:
```
$ make
arm-poky-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/opt/poky/2.1.3/sysroots/cortexa9hf-neon-poky-linux-gnueabi -c -pipe  -O2 -pipe -g -feliminate-unused-debug-types  -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /opt/poky/2.1.3/sysroots/cortexa9hf-neon-poky-linux-gnueabi/usr/include/qt5 -isystem /opt/poky/2.1.3/sysroots/cortexa9hf-neon-poky-linux-gnueabi/usr/include/qt5/QtGui -isystem /opt/poky/2.1.3/sysroots/cortexa9hf-neon-poky-linux-gnueabi/usr/include/qt5/QtCore -I. -I/opt/poky/2.1.3/sysroots/cortexa9hf-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -o obj/keyinjector.o keyinjector.c
keyinjector.c:8:57: fatal error: env.h: No such file or directory
compilation terminated.
Makefile:393: recipe for target 'obj/keyinjector.o' failed
make: *** [obj/keyinjector.o] Error 1
```
Any ideas what could be the culprit?
