### ISSUE TITLE
General Question dealing with emulating screen events

### ISSUE THREAD

**Issue by exabrial** [ddvk/remarkable-touchgestures#3]
This question is sorta unrelated to your project... kinda... So I'd like to be able to turn pages without touching the device... I know sounds crazy. If you're a musician though with both hands on an instrument, this would be invaluable. 

Right now, I have a cheap android tablet, OTG adapter, and an Arduino that emulates keypresses when I stomp on a floor switch. This closes a GPIO pin and causes the Arduino to emulate a arrow key press over USB.

Since the remarkable2 doesn't have a USB Host Mode (yet), I was curious if this could be done with a system daemon over IP. So have a systemd service listen on a UDP socket for events...

My question is, how would one signal to the UI to turn a page? Is emulating a keypress enough? If so, how did you go about solving that problem in your codebase? 

Thanks for any help!

**Comment by ddvk** [comment]
didn't see this comment, but there is a simple hack:
do:
`cat /dev/input/event2 > left` then swipe with finger to the left, press CTRL-C
`cat /dev/input/event2 > right` then swipe with finger to the right, press CTRL-C

then just:
`cat right > /dev/input/event2` will trigger a right swipe
and cat left > ... left

you can do this event via rest, a simple go server that executes this

**Comment by exabrial** [comment]
Brilliant, thank you!
